import jsPDF from "jspdf";

/**
 * Shared PDF generation utilities for Kloer.ai
 */

interface PDFOptions {
  title: string;
  subtitle?: string;
  filename: string;
}

export function createPDF(options: PDFOptions): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(options.title, pageWidth / 2, 20, { align: "center" });

  if (options.subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(options.subtitle, pageWidth / 2, 27, { align: "center" });
    doc.setTextColor(0);
  }

  return doc;
}

export function addSection(doc: jsPDF, title: string, content: string, y: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Check page break
  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(41, 98, 255); // primary blue
  doc.text(title, margin, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0);
  const lines = doc.splitTextToSize(content, maxWidth);
  for (const line of lines) {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 4.5;
  }

  return y + 4;
}

export function addFooter(doc: jsPDF, text: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(text, doc.internal.pageSize.getWidth() / 2, 290, { align: "center" });
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 20, 290, { align: "right" });
  }
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}

/**
 * Generate clinical/case note PDF
 */
export function generateDocumentPDF(opts: {
  formatLabel: string;
  profName: string;
  profOrg: string;
  profReg: string;
  clientName: string;
  sessionDate: string;
  sections: { title: string; content: string }[];
}) {
  const doc = createPDF({ title: opts.formatLabel, subtitle: "Confidential", filename: "document" });
  let y = 35;

  // Professional info
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`${opts.profName} · ${opts.profOrg} · Reg: ${opts.profReg}`, 20, y);
  y += 5;
  doc.text(`Patient: ${opts.clientName} · Date: ${opts.sessionDate}`, 20, y);
  y += 3;

  // Divider
  doc.setDrawColor(200);
  doc.line(20, y, doc.internal.pageSize.getWidth() - 20, y);
  y += 8;

  for (const s of opts.sections) {
    y = addSection(doc, s.title, s.content, y);
  }

  addFooter(doc, `${opts.formatLabel} — Generated by Kloer.ai — ${opts.sessionDate}`);
  downloadPDF(doc, `${opts.formatLabel.replace(/\s/g, "_")}_${opts.clientName.replace(/\s/g, "_")}.pdf`);
}

/**
 * Generate audit trail PDF
 */
export function generateAuditTrailPDF(opts: {
  entries: { time: string; action: string; before?: string; after?: string }[];
  documentTitle: string;
  sessionDate: string;
}) {
  const doc = createPDF({ title: "Audit Trail", subtitle: opts.documentTitle, filename: "audit" });
  let y = 35;

  for (const e of opts.entries) {
    if (y > 265) { doc.addPage(); y = 20; }
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(e.time, 20, y);
    doc.setFontSize(9);
    doc.setTextColor(0);
    doc.text(e.action, 35, y);
    y += 5;
    if (e.before) {
      doc.setFontSize(7);
      doc.setTextColor(180, 50, 50);
      const beforeLines = doc.splitTextToSize(`Before: ${e.before.slice(0, 300)}`, 140);
      for (const l of beforeLines) { doc.text(l, 35, y); y += 3.5; }
      doc.setTextColor(30, 130, 30);
      const afterLines = doc.splitTextToSize(`After: ${(e.after || "").slice(0, 300)}`, 140);
      for (const l of afterLines) { doc.text(l, 35, y); y += 3.5; }
      doc.setTextColor(0);
    }
    y += 2;
  }

  addFooter(doc, `Audit Trail — ${opts.documentTitle} — ${opts.sessionDate}`);
  downloadPDF(doc, `Audit_Trail_${opts.sessionDate.replace(/\s/g, "_")}.pdf`);
}

/**
 * Generate prescription PDF
 */
export function generatePrescriptionPDF(opts: {
  profName: string;
  profOrg: string;
  profReg: string;
  clientName: string;
  sessionDate: string;
  countryFormat: string;
  items: { name: string; dosage: string; form: string; frequency: string; duration: string; quantity: string; instructions: string }[];
}) {
  const doc = createPDF({ title: "Prescription", subtitle: `${opts.countryFormat} Format`, filename: "prescription" });
  let y = 35;

  doc.setFontSize(9);
  doc.text(`Prescriber: ${opts.profName} · ${opts.profOrg} · Reg: ${opts.profReg}`, 20, y); y += 5;
  doc.text(`Patient: ${opts.clientName} · Date: ${opts.sessionDate}`, 20, y); y += 3;
  doc.setDrawColor(200);
  doc.line(20, y, doc.internal.pageSize.getWidth() - 20, y); y += 8;

  for (const rx of opts.items) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(rx.name, 20, y); y += 6;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`Dosage: ${rx.dosage} · Form: ${rx.form} · Frequency: ${rx.frequency}`, 20, y); y += 5;
    doc.text(`Duration: ${rx.duration} · Quantity: ${rx.quantity}`, 20, y); y += 5;
    if (rx.instructions) {
      doc.text(`Instructions: ${rx.instructions}`, 20, y); y += 5;
    }
    y += 4;
  }

  // Signature line
  y += 10;
  doc.setDrawColor(0);
  doc.line(20, y, 80, y);
  doc.setFontSize(8);
  doc.text("Prescriber Signature", 20, y + 4);
  doc.line(110, y, 170, y);
  doc.text("Date", 110, y + 4);

  addFooter(doc, `Prescription — ${opts.countryFormat} — Generated by Kloer.ai`);
  downloadPDF(doc, `Prescription_${opts.clientName.replace(/\s/g, "_")}.pdf`);
}

/**
 * Generate referral letter PDF
 */
export function generateReferralPDF(opts: {
  to: string;
  specialty: string;
  body: string;
  profName: string;
  profOrg: string;
  clientName: string;
  sessionDate: string;
  language: string;
}) {
  const doc = createPDF({ title: "Referral Letter", subtitle: opts.specialty, filename: "referral" });
  let y = 35;

  doc.setFontSize(9);
  doc.text(`To: ${opts.to}`, 20, y); y += 5;
  doc.text(`From: ${opts.profName}, ${opts.profOrg}`, 20, y); y += 5;
  doc.text(`Re: ${opts.clientName} · Date: ${opts.sessionDate}`, 20, y); y += 3;
  doc.setDrawColor(200);
  doc.line(20, y, doc.internal.pageSize.getWidth() - 20, y); y += 8;

  y = addSection(doc, "", opts.body, y);

  addFooter(doc, `Referral Letter — ${opts.specialty} — Generated by Kloer.ai`);
  downloadPDF(doc, `Referral_${opts.specialty.replace(/\s/g, "_")}.pdf`);
}

/**
 * Generate pilot agreement PDF
 */
export function generatePilotAgreementPDF(opts: {
  yourName: string;
  yourOrg: string;
  partnerContact: string;
  partnerOrg: string;
  startDate: string;
  endDate: string;
  weeks: number;
  pilotUsers: string;
  useCase: string;
  specialConditions: string;
}) {
  const doc = createPDF({ title: "Pilot Agreement — Kloer.ai", subtitle: "Confidential", filename: "pilot-agreement" });
  let y = 35;

  const margin = 20;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Between:", margin, y); y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(`${opts.yourName}${opts.yourOrg ? `, ${opts.yourOrg}` : ""} ("Provider")`, margin, y); y += 7;
  doc.setFont("helvetica", "bold");
  doc.text("And:", margin, y); y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(`${opts.partnerContact}, ${opts.partnerOrg} ("Partner")`, margin, y); y += 10;

  doc.text(`Purpose: Pilot testing of the Kloer.ai platform for ${opts.useCase}.`, margin, y); y += 5;
  doc.text(`Duration: ${opts.startDate} to ${opts.endDate} (${opts.weeks} weeks)`, margin, y); y += 5;
  doc.text(`Pilot Users: ${opts.pilotUsers} user${parseInt(opts.pilotUsers) !== 1 ? "s" : ""} at ${opts.partnerOrg}`, margin, y); y += 10;

  doc.setFont("helvetica", "bold");
  doc.text("Terms:", margin, y); y += 6;
  doc.setFont("helvetica", "normal");
  const terms = [
    "The platform is provided free of charge during the pilot period.",
    `Partner agrees to provide honest feedback within ${Math.max(2, Math.floor(opts.weeks / 2))} weeks of pilot end.`,
    "Partner data remains private and is not shared with third parties.",
    "Audio is processed locally and deleted by default — no recordings stored on external servers.",
    "Either party may end the pilot at any time.",
    "This agreement does not create any financial obligation.",
  ];
  terms.forEach((t, i) => {
    doc.text(`${i + 1}. ${t}`, margin + 4, y);
    y += 5;
  });

  if (opts.specialConditions) {
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Special Conditions:", margin, y); y += 5;
    doc.setFont("helvetica", "normal");
    const scLines = doc.splitTextToSize(opts.specialConditions, 160);
    for (const l of scLines) { doc.text(l, margin, y); y += 4.5; }
  }

  // Signature blocks
  y += 20;
  doc.setDrawColor(0);
  doc.line(margin, y, 80, y);
  doc.setFontSize(8);
  doc.text(opts.yourName, margin, y + 4);
  doc.text(opts.yourOrg || "Provider", margin, y + 8);

  doc.line(110, y, 170, y);
  doc.text(opts.partnerContact, 110, y + 4);
  doc.text(opts.partnerOrg, 110, y + 8);

  y += 20;
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`Date: ${opts.startDate}`, doc.internal.pageSize.getWidth() / 2, y, { align: "center" });

  addFooter(doc, "Pilot Agreement — Kloer.ai — Confidential");
  downloadPDF(doc, `Pilot_Agreement_${opts.partnerOrg.replace(/\s/g, "_")}.pdf`);
}

/**
 * Generate grant reporting PDF
 */
export function generateGrantReportPDF(opts: {
  period: string;
  beneficiaries: number;
  casesManaged: number;
  languagesSupported: number;
  referralsMade: number;
  casesByType: { type: string; count: number; pct: number }[];
  needsCategories: { category: string; count: number }[];
  languages: string[];
}) {
  const doc = createPDF({ title: "Grant Report", subtitle: `Period: ${opts.period}`, filename: "grant-report" });
  let y = 35;
  const margin = 20;

  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("All data is anonymised. No personal information is included.", doc.internal.pageSize.getWidth() / 2, y, { align: "center" });
  doc.setTextColor(0);
  y += 10;

  // Summary stats
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Summary Statistics", margin, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Beneficiaries Supported: ${opts.beneficiaries}`, margin, y); y += 5;
  doc.text(`Cases Managed: ${opts.casesManaged}`, margin, y); y += 5;
  doc.text(`Languages Supported: ${opts.languagesSupported}`, margin, y); y += 5;
  doc.text(`Referrals Made: ${opts.referralsMade}`, margin, y); y += 10;

  // Cases by type
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Cases by Type", margin, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  for (const c of opts.casesByType) {
    doc.text(`${c.type}: ${c.count} (${c.pct}%)`, margin + 4, y); y += 5;
  }
  y += 5;

  // Needs
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Needs Identified", margin, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  for (const n of opts.needsCategories) {
    doc.text(`${n.category}: ${n.count}`, margin + 4, y); y += 5;
  }
  y += 5;

  // Languages
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Languages Supported", margin, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(opts.languages.join(", "), margin + 4, y);

  addFooter(doc, "Grant Report — Anonymised Data — Generated by Kloer.ai");
  downloadPDF(doc, `Grant_Report_${opts.period.replace(/\s/g, "_")}.pdf`);
}
